name: listing, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node modules
      uses: npm install
    - name: Build production project
      uses: npm run build:prod
    - name: Linting TS
      uses: npm run lint:ts
    - name: Linting CSS
      uses: npm run lint:scss
    - name: unit testing
      uses: npm run test:unit
    - name: build storybook
      uses: npm run storybook:build
    - name: screenshot test
      uses: npm run test:ui:ci
